# Generated by Django 3.1.5 on 2021-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=30, verbose_name='Name')),
                ('userComment', models.CharField(max_length=300, verbose_name='Comment')),
            ],
        ),
    ]
