# Generated by Django 3.1.5 on 2021-01-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210105_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertName', models.CharField(max_length=30, verbose_name='expertName')),
                ('expertCompany', models.CharField(max_length=30, verbose_name='expertCompany')),
                ('review', models.CharField(max_length=300, verbose_name='expertReview')),
            ],
        ),
    ]
